# Site settings
title: Deep Learnig Boun
tag_text: Deep Learning Boun
description: The Curated List of Deep Learning Resource by Boun

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
