# Site settings
title: Deep Learning Boun
tag_text: Deep Learning Boun
description: The Curated List of Deep Learning Resources by Boun

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
